# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path:     /blog/viewUserPage
            logout:
                path:       fos_user_security_logout
                target:     /blog/index
            remember_me:
                key:        %secret% 
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
         - { path: ^/blog/viewUserPage, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }
#        - { path: ^/viewUserPage, role: [ROLE_USER, IS_AUTHENTICATED_FULLY] }
         - { path: ^/admin, role: [ROLE_ADMIN] }
        
    encoders:
        ZD\UserBundle\Entity\User: sha512