<?php

namespace ZD\AdminBundle\Entity;

/**
 * UserPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPageRepository extends \Doctrine\ORM\EntityRepository
{
}
