zd_blog_home:
#    path: /index
#    defaults:  { _controller: ZDBlogBundle:Article:index }
    path:      /{page}
    defaults:
        _controller: ZDBlogBundle:Article:index
        page:        1
    
zd_blog_view:
    path: /article
    defaults:  { _controller: ZDBlogBundle:Article:view}
    
zd_blog_register:
    path: /register
    defaults:  { _controller: ZDBlogBundle:Article:register }
    
zd_blog_login:
    path: /login
    defaults:  { _controller: ZDBlogBundle:Article:login }
    
zd_blog_add:
    path: /add
    defaults:  { _controller: ZDBlogBundle:Article:add }
    
#zd_blog_edit:
#    path: /edit/{id}
#    defaults: {_controller: ZDBlogBundle:Article:edit}
#    requirements:
#        id: \d*
#    
#zd_blog_delete:
#    path: /delete/{id}
#    defaults: {_controller: ZDBlogBundle:Article:delete}
#    requirements:
#        id: \d*
#    
    