<?php

namespace ZD\BlogBundle\Entity;

/**
 * FormLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
