<?php

namespace ZD\BlogBundle\Entity;

/**
 * FormRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
