zd_admin_homepage:
    path:     /admin
    defaults: { _controller: ZDAdminBundle:Admin:index }
    
zd_admin_view:
    path:     /view/
    defaults: { _controller: ZDAdminBundle:Admin:view }
    
zd_admin_addDay:
    path:     /addDay
    defaults: { _controller: ZDAdminBundle:Admin:addDay}
    
zd_admin_viewHome:
    path:   /viewHome
    defaults: { _controller: ZDAdminBundle:Admin:viewHome}
    
zd_admin_addHome:
    path:   /addHome
    defaults: { _controller: ZDAdminBundle:Admin:addHome}
