zd_admin_homepage:
    path:     /admin
    defaults: { _controller: ZDAdminBundle:Admin:index }
    
zd_admin_view:
    path:     /view/
    defaults: { _controller: ZDAdminBundle:Admin:view }
    
    
zd_admin_viewDay:
    path:   /viewDay
    defaults: { _controller: ZDAdminBundle:Admin:viewDay}
    
zd_admin_addDay:
    path:     /addDay
    defaults: { _controller: ZDAdminBundle:Admin:addDay}
    
zd_admin_editDay:
    path:   /editDay/{id}
    defaults: { _controller: ZDAdminBundle:Admin:editDay}
    
zd_admin_deleteDay:
    path:   /deleteDay/{id}
    defaults: { _controller: ZDAdminBundle:Admin:deleteDay}
    
zd_admin_viewHome:
    path:   /viewHome
    defaults: { _controller: ZDAdminBundle:Admin:viewHome}
    
zd_admin_addHome:
    path:   /addHome
    defaults: { _controller: ZDAdminBundle:Admin:addHome}
    
zd_admin_editHome:
    path:   /editHome/{id}
    defaults: { _controller: ZDAdminBundle:Admin:editHome}
    
zd_admin_deleteHome:
    path:   /deleteHome/{id}
    defaults: { _controller: ZDAdminBundle:Admin:deleteHome}
    
    
zd_week_viewWeek:
    path:   /viewWeek/{weekId}
    defaults: { _controller: ZDAdminBundle:Week:viewWeek}
    

